// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "df11e588-d09b-4e4e-acba-e5047724cca0");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1545227831);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1545227952);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1545235279);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1545227591);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1545227259);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1545227711);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1545228192);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1545228072);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1545227109);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e12d61cd-189c-4be0-a2a7-fce64cd1fa16}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1545170400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1545235254200");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1545237028200");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1545235254992");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1545238854992");
user_pref("browser.search.region", "UA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181207224003");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1545235251");
user_pref("browser.slowStartup.averageTime", 4034);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20181207224003");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1545227116351");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "06b5ce6140624bb7a6727fc8e9501dbf");
user_pref("extensions.blocklist.lastModified", "Fri, 14 Dec 2018 18:16:38 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1545227834);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181207224003");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{1e2c348d-026f-4cd0-9c13-4b274437c17b}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"321b7e0d-c4f1-411e-bc62-4e3e85bd8954\",\"screenshots@mozilla.org\":\"bb41a89d-d8c9-48fa-9836-1ecaa30ebe54\",\"webcompat-reporter@mozilla.org\":\"3f1ca963-78d5-4fd5-8665-2b3ad84d2abc\",\"webcompat@mozilla.org\":\"c4aff466-56e1-4d63-8e7e-2f1ec0400993\",\"fxmonitor@mozilla.org\":\"6a422322-e08c-4d75-a047-f15334e7db8b\"}");
user_pref("idle.lastDailyNotification", 1545228055);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1545227764);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181207224003");
user_pref("media.gmp-manager.lastCheck", 1545227763);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1545228055);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "14892a8c-e9fe-4bec-954d-632eabbcc04e");
user_pref("security.sandbox.plugin.tempDirSuffix", "d5dcdcce-aa92-4de7-abcf-a0382453aa8b");
user_pref("services.blocklist.addons.checked", 1545227897);
user_pref("services.blocklist.gfx.checked", 1545227897);
user_pref("services.blocklist.onecrl.checked", 1545227897);
user_pref("services.blocklist.pinning.checked", 1545227897);
user_pref("services.blocklist.plugins.checked", 1545227897);
user_pref("services.settings.clock_skew_seconds", -185);
user_pref("services.settings.last_update_seconds", 1545227897);
user_pref("services.settings.main.language-dictionaries.last_check", 1545227897);
user_pref("services.settings.main.onboarding.last_check", 1545227897);
user_pref("services.settings.main.sites-classification.last_check", 1545227897);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1545228055);
user_pref("toolkit.startup.last_success", 1545235248);
user_pref("toolkit.telemetry.cachedClientID", "9767bd0a-478a-41c7-a68c-103d265e2404");
user_pref("toolkit.telemetry.previousBuildID", "20181207224003");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
